import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import MainIntroduce from "./components/main/MainIntroduce";

export default function Home() {
  return (
    <>
      <Head>
        <title>Archiving for Hannah</title>
        <meta name="description" content="Generated by Hannah" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sacramento" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <MainIntroduce />
      </main>
      <Footer />
    </>
  )
}
